# Generated by Django 5.0.3 on 2024-03-11 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb')),
                ('category', models.CharField(choices=[('ACAO', 'Ação'), ('TERROR', 'Terror'), ('COMEDIA', 'Comedia'), ('Outros', 'Outros')], max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('preview', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
